# Generated by Django 2.2.4 on 2019-12-02 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0002_tournament_time_start'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='school',
            field=models.CharField(default='', max_length=100),
        ),
    ]
