# Generated by Django 2.2.4 on 2020-01-15 23:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0004_auto_20191231_0509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='area',
            field=models.CharField(choices=[('Świętokrzyskie', 'Świętokrzyskie'), ('Podkarpackie', 'Podkarpackie')], max_length=100, verbose_name='Województwo'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Autor'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='content',
            field=models.TextField(verbose_name='Opis'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='date_posted',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data dodania'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='date_start',
            field=models.DateField(blank=True, null=True, verbose_name='Data startu'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='first_place',
            field=models.CharField(default='', max_length=100, verbose_name='Pierwsze miejsce'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='school',
            field=models.CharField(default='', max_length=100, verbose_name='Szkoła'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='second_place',
            field=models.CharField(default='', max_length=100, verbose_name='Drugie miejsce'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='third_place',
            field=models.CharField(default='', max_length=100, verbose_name='Trzecie miejsce'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='time_start',
            field=models.TimeField(blank=True, null=True, verbose_name='Godzina startu'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Tytuł'),
        ),
    ]
